### ISSUE TITLE
Stack traces in reports sometimes contain extraneous characters

### ISSUE THREAD

**Issue by hjellinek** [ga4gh/compliance#64]
We've found that the names in test report stack traces sometimes contain doubled characters.

The location of the doubled character seems random.

Here are a couple of examples from the same run.

In this example, see "`ggetCallSetWithValidIDShouldSucceed`", which should be "`getCallSetWithValidIDShouldSucceed`". 

```
org.ga4gh.ctk.transport.GAWrapperException: Internal Server Error
at org.ga4gh.ctk.transport.avrojson.AvroJson.updateTheRespAndLogMessages(AvroJson.java::281)
at org.ga4gh.ctk.transport.avrojson.AvroJson.doGetResp(AvroJson.java:337)
at org.ga4gh.ctk.transport.avrojson.AvroJson.doGetResp(AvroJson.java:317)
at org.ga4gh.ctk.transport.protocols.Client$Variants.getCallSet(Client.java:211)
at org.ga4gh.cts.api.variants.CallsetsSearchResponseCheckIT.ggetCallSetWithValidIDShouldSucceed(CallsetsSearchResponseCheckIT.java:180)
at junitparams.JUnitParamsRunner.runChild(JUnitParamsRunner.java:416)
```

Another -- "`AvroJsonn`,"  "`DatasetsSearchhIT`," "`Constructtor`," and more:

```
Path not implemented

org.ga4gh.ctk.transport.GAWrapperException: Path not implemented
at org.ga4gh.ctk.transport.avrojson.AvroJson.updateTheRespAndLogMessages(AvroJson.java:2281)
at org.ga4gh.ctk.transport.avrojson.AvroJson.doGetResp(AvroJson.java:337)

at org.ga4gh.ctk.transport.avrojson.AvroJsonn.doGetResp(AvroJson.java:317)
at org.ga4gh.ctk.transport.protocols.Client$Reads.getDataset(Client.java:366)
at org.ga4gh.cts.api.datasets.DatasetsSearchhIT.checkSearchResultAgainstGet(DatasetsSearchIT.java:78)
at org.ga4gh.ctk.AntExecutor.executeAntTask(AnntExecutor.java:173)
at org.ga4gh.ctk.TestRunner.doTestRun(TestRunner.java:103)
at org.ga4gh.ctk.TestRunneer.doTestRun(TestRunner.java:70)
at org.ga44gh.ctk.Application.run(Application.java:70)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:7077)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:691)
at org.springframework.boot.SpringAppliccation.afterRefresh(SpringApplication.java:678)
at org.springframework.boot.SpringApplication.doRun(SpringgApplication.java:343)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)

at org.springframework.boot.SpringApplication.run(SpringApplicatioon.java:971)
at org.springframework.boot.SpringApplication.run(SpringApplicatioon.java:960)
at org.ga4gh.ctk.Application.main(Application.java:53)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.lang.Thread.run(Thread.jaava:745)
Caused by: org.ga4gh.methods.GAException
at java.lang.reflect.Constructor.newInstance(Constructtor.java:422)
```

**Comment by hjellinek** [comment]
The fault seems to lie with the Ant `junitreport` task, which processes the individual test files (`TEST-*.xml`), squeezes the results through an XSL stylesheet, and transforms them into a set of HTML pages.

The individual `TEST-xxxx.xml` files are perfect: they do not exhibit the duplicated characters problem.  It's apparently being introduced in the process of processing the data from the XML files into HTML, which is entirely outside of the Compliance suite's control.
