### ISSUE TITLE
'stubbing out future comms' has confusing behavior

### ISSUE THREAD

**Issue by calbach** [ga4gh/compliance#81]
```
[o.g.c.t.a.AvroJson ] stubbing future comms due to problem communicating JSON with http://localhost:8090/variants/search
```

I would prefer this behavior were removed entirely - tests should ideally be completely independent of one another, aside from required setup/teardown.

I've observed this happening when the integration test receives an unexpected 400 error. The result is that all subsequent test cases fail as well in an opaque manner (mostly with null pointer exceptions). Often times, the issue has been that the Google API returns a 400 (invalid argument) where the client expected something like a 404 - these cases arise frequently where the spec is unclear.

Example NPE following that message:
```
java.lang.NullPointerException cannot be cast to org.ga4gh.ctk.transport.GAWrapperException

java.lang.ClassCastException: java.lang.NullPointerException cannot be cast to org.ga4gh.ctk.trransport.GAWrapperException
at org.ga4gh.cts.api.Utils.catchGAWrapperExcepption(Utils.java:316)
at org.ga4gh.cts.api.variants.VariantsMethodsEndpointAliveIT.testSearchVariantsForNonexistentReferenceFails(VariantsMethodsEndpointAliveIT.java:46)
at org.ga4gh.ctk.AntExecutor.executeAntTask(AntExecutor.java:173)
at org.ga4gh.ctk.TestRunner.doTestRun(TestRunner.java:103))
at org.ga4gh.ctk.TestRunner.doTestRun(TestRunner.java:70)
at org.ga4gh.ctk.Application.run(Application.java:70)
at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:707)
at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:691)
at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:678)
at org.springframework.boot.SpringApplication.doRun(SpringApplication.javaa:343)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:273)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:971)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:960)
at org.ga4gh.ctk.Application.main(Application.javaa:53)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:53)
at java.lang.Thread..run(Thread.java:745)
```

**Comment by diekhans** [comment]
this is a bug  in the CTK  passing to Herb.

**Comment by hjellinek** [comment]
Agreed, I find this feature counterproductive.

**Comment by calbach** [comment]
Thanks @hjellinek. Tested the change out and this makes life much easier.
